# Create your views here.

from django.contrib.auth.decorators import login_required
# from django.http import HttpResponse
from django.shortcuts import render
from member.models import Member
from models import Blog
import logging

logger = logging.getLogger('curve')

@login_required
def recent(request):
    """ Get member's recent blogs. """
    userid = request.session['userid']
    member = Member.objects.get_member(userid)
    context = {}
    context['blogs'] = createDummyBlogs(member, 5)
    context['ajax'] = request.is_ajax()
    return render(request, 'blog/recent.html', context)

def createDummyBlogs(member, count):
    """ Create dummy blogs created by member. """
    blogs = []
    for index in range(count):
        blog = Blog(member, 'Sample blog ' + str(index), 'This is a sample blog generated by server.')
        blogs.append(blog)
        pass
    return blogs
